
version: 2 
jobs:
  deploy:
    docker:
      - image: pionux/build-deploy:0.1
    steps:
      - run:
          name: "Deploy hugo"
          command: |
            git clone https://github.com/hongsea/test-hugo.git
            cd test-hugo && hugo -D
            cd .. && touch hugo
            echo $hugo > hugo
            chmod +x hugo && ./hugo
workflows:
   version: 2
   build:
     jobs:
       - deploy
